services:
    - type: web
      name: eastpark-backend
      runtime: docker
      plan: free
      region: frankfurt
      dockerfilePath: ./Dockerfile
      dockerContext: .
      healthCheckPath: /health
      autoDeployTrigger: commit
      envVars:
          - key: NODE_ENV
            value: production
          - key: APP_ENV
            value: production
          - key: APP_URL
            sync: false
          - key: APP_CORS_ORIGINS
            value: https://eastpark-web-app.vercel.app
          - key: APP_LOG_LEVEL
            value: info
          - key: HTTP_HOST
            value: 0.0.0.0
          - key: HTTP_PORT
            value: 10000
          - key: AUTH_ACCESS_TOKEN_EXP
            value: 15m
          - key: AUTH_REFRESH_TOKEN_EXP
            value: 7d
          - key: AUTH_ACCESS_TOKEN_SECRET
            sync: false
          - key: AUTH_REFRESH_TOKEN_SECRET
            sync: false
          - key: DATABASE_URL
            sync: false
          - key: DIRECT_DATABASE_URL
            sync: false
          - key: REDIS_URL
            sync: false
          - key: SMTP_HOST
            value: smtp-relay.brevo.com
          - key: SMTP_PORT
            value: 587
          - key: SMTP_USER
            sync: false
          - key: SMTP_PASS
            sync: false
          - key: EMAIL_FROM
            value: noreply@eastpark.app
          - key: SUPABASE_URL
            sync: false
          - key: SUPABASE_SERVICE_KEY
            sync: false
          - key: SUPABASE_BUCKET
            value: eastpark-uploads
          - key: PAYMOB_API_KEY
            sync: false
          - key: PAYMOB_HMAC_SECRET
            sync: false
          - key: PAYMOB_INTEGRATION_ID
            sync: false
          - key: PAYMOB_IFRAME_ID
            sync: false
